excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - emogiphy/Thirdparty/SweetAlert.swift

line_length:
  warning: 200

file_length:
  warning: 500
  error: 1200

disabled_rules:
  - type_body_length
